
# Default endpoint URLs for the ORCID OAuth API


production:
  site: http://api.orcid.org
  authorize_url: http://orcid.org/oauth/authorize
  token_url: http://api.orcid.org/oauth/token
  client_id: 
  client_secret: 

development:
  site: http://api.devsandbox.orcid.org
  authorize_url: http://devsandbox.orcid.org/oauth/authorize
  token_url: http://api.devsandbox.orcid.org/oauth/token
  client_id: 
  client_secret: 
